# Generated by Django 5.0.4 on 2024-04-22 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_stripe_id_alter_user_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="facebook_login_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="google_login_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_social",
        ),
        migrations.RemoveField(
            model_name="user",
            name="modified_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stripe_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="Password"),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, verbose_name="Is email verified"
                    ),
                ),
                ("dob", models.DateField()),
                (
                    "stripe_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Stripe ID"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_images/",
                        verbose_name="Profile Image",
                    ),
                ),
                (
                    "is_social",
                    models.BooleanField(default=False, verbose_name="Is social"),
                ),
                (
                    "google_login_token",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Google Login Token",
                    ),
                ),
                (
                    "facebook_login_token",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Facebook Login Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="users.profile",
                        verbose_name="Created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_modified",
                        to="users.profile",
                        verbose_name="Created by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
